name: dotup_dart_utils
description: A small dart package with common helpers.
version: 4.0.0
homepage: https://dotup.de
repository: https://github.com/dotupNET/dotup_dart_utils

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
