name: dotup_dart_utils
description: A small dart package with common helpers.
version: 3.0.0
homepage: https://dotup.de
repository: https://github.com/dotupNET/dotup_dart_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
